version: "3.9"
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb2
    networks:
      - internal
    ports:
      - "8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    env_file:
      - .env

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal
      - external
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./app/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SECURITY_ALLOW_EMBEDDING: ${GRAFANA_SECURITY_ALLOW_EMBEDDING}
      GF_AUTH_ANONYMOUS_ENABLED: ${GRAFANA_AUTH_ANONYMOUS_ENABLED}
      GF_AUTH_ANONYMOUS_ORG_ROLE: ${GRAFANA_AUTH_ANONYMOUS_ORG_ROLE}
      GF_SERVER_ROOT_URL: ${GRAFANA_SERVER_ROOT_URL}
      GF_SERVER_SERVE_FROM_SUB_PATH: ${GRAFANA_SERVER_SERVE_FROM_SUB_PATH}
    command: >
      /bin/bash -c "
      envsubst < /etc/grafana/provisioning/datasources/datasources.yaml > /etc/grafana/provisioning/datasources/datasources.yaml &&
      /run.sh
      "
    env_file:
      - .env
    depends_on:
      - influxdb

  fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - "8080"
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    env_file:
      - .env
    depends_on:
      - influxdb
      - grafana

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  influxdb_data:
  grafana-storage:
